export const KNOWN_PATHS = [
  "/",
  "/home",
  "/chat",
  "/login",
  "/nutrition",
  "/restaurants",
  "/recipes",
  "/glp1",
  "/exercise",
  "/hydration",
  "/habits",
  "/explore",
  "/saved",
  "/blueprint",
  "/history",
  "/provider-questions",
  "/grocery-list",
  "/travel",
  "/profile",
  "/admin",
  "/settings",
  "/safety",
  "/marketing",
] as const;

export type KnownPath = (typeof KNOWN_PATHS)[number];

export const NAV_LABELS: Record<KnownPath, string> = {
  "/": "Home",
  "/home": "Home",
  "/chat": "Chat",
  "/login": "Log In",
  "/nutrition": "Nutrition",
  "/restaurants": "Restaurants",
  "/recipes": "Recipes",
  "/glp1": "GLP-1 Education",
  "/exercise": "Exercise & Movement",
  "/hydration": "Hydration",
  "/habits": "Healthy Habits",
  "/explore": "Explore",
  "/saved": "Saved",
  "/blueprint": "My Blueprint",
  "/history": "History",
  "/provider-questions": "Provider Questions",
  "/grocery-list": "Grocery List",
  "/travel": "Travel",
  "/profile": "Profile",
  "/admin": "Admin",
  "/settings": "Settings",
  "/safety": "Help & Safety",
  "/marketing": "Marketing",
};
